services:
  - type: web
    name: trader-naaz-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_USERNAME
        value: "@Naaz_Khan78"
      - key: SIGNUP_LINK
        value: "https://broker-qx.pro/sign-up/?lid=1143940"
